[package]
name = "echo"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.36"

[package.metadata.component]
package = "uzimaru:echo"

[package.metadata.component.dependencies]
